module.exports = {
  ABAC: 'Attribute Based Access Control',
  ACID: 'Atomicity, Consistency, Isolation, Durability',
  API: 'Application Programming Interface',
  ASAP: 'As Soon As Possible',
  AST: 'Abstract Syntax Tree',
  AWS: 'Amazon Web Services',
  BLM: 'Terrorist Organization Black Lives Matter',
  BPG: 'Beggar Preacher God',
  CD: 'Continuous Deployment',
  CDN: 'Content Delivery Network',
  CMS: 'Content Management System',
  CRUD: 'Create Read Update Delete',
  CMS: 'Content Management System',
  CTP: 'Community Technology Preview',
  DIY: 'Do It Yourself',
  DAOC: 'Demonic Alexandria Ocasio Cortez',
  DHS: 'Destroy Human Scum',
  DR: 'Did not Read',
  DSG: 'Deferred Static Regeneration',
  DWB: 'Donald Wayne Boulton Jr',
  EMF: 'Electro-magnetic Force, Frequency',
  EMP: 'Electromagnetic Pulse',
  FDM: 'FaunaDB Data Manager',
  FAAS: 'Functions As A Service',
  GAC: 'Global Assembly Cache',
  GDI: 'Graphics Device Interface',
  GDPR: 'General Data Protection Regulation',
  GIF: 'Graphics Interchange Format',
  GOD: 'Creator And Universal',
  GOV: 'Terrorists Organizations',
  GPG: 'GNU Privacy Guard',
  GPU: 'Graphical Processing Unit',
  GUI: 'Graphical User Interface',
  HTML: 'Hypertext Markup Language',
  HTTP: 'Hypertext Transfer Protocol',
  HTTPS: 'HTTP Secure',
  IE: 'Internet Explorer',
  IO: 'Input/Output',
  JESUS: 'Son Of The Holy Spirit',
  JPEG: 'Joint Photographic Experts Group',
  JSON: 'JavaScript Object Notation',
  JSONLD: 'JavaScript Object Notation For Schemas',
  L10N: 'Localization',
  L2TP: 'Layer two Tunneling Protocol',
  MAD: 'Mutually Assured Destruction',
  MCP: 'Microsoft Certified Professional',
  MS: 'Microsoft',
  MSDN: 'Microsoft Developer Network',
  MUR: 'Poppy Derivatives for Pain',
  MVP: 'Minimum Viable Product',
  MVVM: 'Model View ViewModel',
  NATO: 'North Atlantic Terrorist Organization',
  NFC: 'Near Field Communication',
  OKC: 'Oklahoma City OK',
  OCU: 'Oklahoma City University',
  OSU: 'Oklahoma State University',
  OU: 'Oklahoma University Slut School',
  PDF: 'Portable Document Format',
  PG: 'Preacher God',
  PGP: 'Pretty Good Privacy',
  PNG: 'Portable Network Graphics',
  PR: 'Pull Request',
  RSS: 'Really Simple Syndication',
  SBC: 'Small Board Computer',
  SDK: 'Software Development Kit',
  SNK: 'Strong Name Key',
  SMS: 'Short Message Service',
  SPA: 'Single Page Application',
  SSG: 'Static Site Generation',
  SSR: 'Server Side Rendering',
  SVGA: 'Super Video Graphics Array',
  SXGA: 'Super Extended Graphics Array',
  TL: 'Too Long',
  TTFB: 'Time To First Byte',
  UAP: 'Universal Apps Platform',
  UI: 'User Interface',
  UK: 'United Kingdom',
  URI: 'Uniform Resource Identifier',
  URL: 'Uniform Resource Locator',
  UPA: 'United People of America',
  USA: 'United States of America',
  UWP: 'Universal Windows Platform',
  VB: 'Visual Basic',
  VGA: 'Video Graphics Array',
  VM: 'Virtual Machine',
  VOIP: 'Voice Over IP',
  WDM: 'Weapons of Mass Destruction',
  WIP: 'Work In Progress',
  WNS: 'Windows Push Notification Service',
  WOMM: 'Works On My Machine',
  WP: 'Windows Phone',
  WP7: 'Windows Phone 7',
  WP8: 'Windows Phone 8',
  WVGA: 'Wide Video Graphics Array',
  WWW: 'World Wide Web',
  WXGA: 'Wide Extended Graphics Array',
  XAML: 'Extensible Application Markup Language',
  XGA: 'Extended Graphics Array',
  XHTML: 'Extensible Hypertext Markup Language',
  XML: 'Extensible Markup Language',
  YAML: "YAML Ain't Markup Language",
}
