[build]
  publish = "public"
  command = "gatsby build"
  NETLIFY_USE_YARN = "true"
[build.environment]
  NODE_VERSION = "16.16.0"
  YARN_VERSION = '1.22.19' 
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = '''
	  public,
	  max-age=2592000'''
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = '''
      https://publiuslogic.com,
      https://graphql.fauna.com,
      https://graphql.fauna.com/graphql
      https://img.badgesize.io/, 
      https://www.unpkg.com/use-sound/dist/use-sound.esm.js.svg, 
      https://www.google-analytics.com/analytics.js,
      https://www.googletagmanager.com/gtag/js
      https://static.doubleclick.net, 
      https://cdn.viglink.com, 
      https://github.com, 
      https://bitbucket.status.atlassian.com, 
      https://links.services.disqus.com, 
      https://img.shields.io, 
      https://secure.gravatar.com, 
      https://identity.netlify.com, 
      https://media-library.cloudinary.com, 
      https://withspectrum.github.io, 
      https://cdn.rawgit.com https://api.bitbucket.org, 
      https://widget.cloudinary.com, 
      https://www.youtube.com, 
      https://www.youtube.de, 
      https://cdn.lr-ingest.io, 
      https://d33wubrfki0l68.cloudfront.net, 
      https://www.googletagmanager.com,
      https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js,
      https://i.ytimg.com, 
      https://fonts.gstatic.com, 
      https://www.google-analytics.com, 
      https://storage.googleapis.com, 
      https://yt3.ggpht.com, 
      https://ocsp.digicert.com, 
      https://graph.facebook.com, 
      https://api.tumblr.com, 
      https://www.reddit.com, 
      https://googleads.g.doubleclick.net, 
      https://static.doubleclick.net, 
      https://api.applause-button.com, 
      https://apis.google.com, 
      https://r.lr-ingest.io, 
      https://connect.facebook.net, 
      https://res.cloudinary.com, 
      https://i.ytimg.com,
      https://api.github.com
      https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
      https://stats.g.doubleclick.net/
      https://www.google.com/recaptcha/api.js
      https://www.gstatic.com/recaptcha/releases/0aeEuuJmrVqDrEL39Fsg5-UJ/recaptcha__en.js
      https://www.gstatic.com/recaptcha/releases/kcXVPRWG7fMILHmzon0--fD3/recaptcha__en.js
      https://unpkg.com/leaflet@1.8.0/dist/leaflet.css
    '''      
    Access-Control-Allow-Methods = '''
      POST, 
      GET,
      PUT,  
      DELETE,
      PATCH,
      OPTIONS,
      HEAD
    '''
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Time-Zone"
    Access-Control-Max-Age = "3600"
    Vary = "Accept-Encoding"
    Permissions-Policy = '''
      accelerometer=(self),
      autoplay=*,
      camera=(self),
      encrypted-media=(self),
      fullscreen=*,
      geolocation=*,
      gyroscope=(self),
      magnetometer=(self),
      microphone=(self),
      midi=(self),
      payment=(self),
      picture-in-picture=*,
      usb=(self)
    '''
[[redirects]]
  from = "/privacy"
  to = "/blog/privacy"
  status = 301
  force = true

[[redirects]]
  from = "/about"
  to = "/blog/about"
  status = 301
  force = true  