backend:
  name: git-gateway
  branch: master
  repo: donaldboulton/publiuslogic-netlify
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
local_backend: true
media_folder: static/img
public_folder: img
identity_url: "https://publiuslogic.com/.netlify/identity"
gateway_url: "https://publiuslogic.com/.netlify/git"
site_domain:  "https://publiuslogic.com/"
squash_merges: true

display_url: https://publiuslogic.com
logo_url: https://publiuslogic.com/img/apple-touch-icon-180x180.png

publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: 'mdx'
    create: true
    slug: 'index'
    media_folder: 'static/img'
    public_folder: 'img'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { name: path, label: Path, widget: "string" }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, widget: "string" }
      - { name: description, label: Description, widget: "string" }
      - { name: body, label: Body, widget: markdown }
      - { name: "imageLink", label: "Image", widget: "string"}
      - name: tags
        label: Tags
        widget: tags
        separator: ","
        required: false
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        choose_url: true
        default: "../static/img/apple-touch-icon-76x76.png"
        media_library:
          config:
            multiple: true