backend:
  name: git-gateway
  branch: master
  repo: donaldboulton/publiuslogic.com-netlify
  
media_folder: static/img
public_folder: /img
identity_url: "https://publiuslogic.com/.netlify/identity"
site_domain:  "https://publiuslogic.com/"
squash_merges: true

display_url: https://publiuslogic.com
logo_url: https://publiuslogic.com/img/apple-touch-icon-180x180.png

publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: 'mdx'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - name: tags
        label: Tags
        widget: tags
        separator: ","
        required: false